/bin/sh: 1: /home/andrewy/SlackBot/SAM-SX/reminder.py: Permission denied
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 110, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 88, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 112, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 90, in read_sheet
    flow = InstalledAppFlow.from_client_secrets_file('test.json', SCOPES)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.json'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 113, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_local_server(port=0)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
  File "/usr/lib/python3.10/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 113, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_local_server(port=0)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
  File "/usr/lib/python3.10/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 113, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_local_server(port=0)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
  File "/usr/lib/python3.10/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 113, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_local_server(port=0)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
  File "/usr/lib/python3.10/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 114, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_console()
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 114, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 92, in read_sheet
    credentials = flow.run_console()
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
Traceback (most recent call last):
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 114, in <module>
    need_to_pay = read_sheet()
  File "/home/andrewy/SlackBot/SAM-SX/reminder.py", line 93, in read_sheet
    credentials = flow.run_local_server(port=0)
  File "/home/andrewy/.local/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
  File "/usr/lib/python3.10/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
